# Alternative Netlify configuration for deployment issues

[build]
  publish = "dist/public"
  command = "npm install && npx vite build && cp public/_redirects dist/public/_redirects || echo '/*    /index.html   200' > dist/public/_redirects"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false